### ISSUE TITLE
Failed to execute script 'server' due to unhandled exception: VIGEM_ERROR_BUS_NOT_FOUND

### ISSUE THREAD

**Issue by XanderL99** [helloparthshah/StadiaWireless#15]
When launching the "server.exe" I get a popup with following error:

title error screen: "Unhandled exception in script"
Failed to execute script 'server' due to unhandled exception: VIGEM_ERROR_BUS_NOT_FOUND
Traceback (most recent call last):
  File "server.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "vgamepad\__init__.py", line 1, in <module>
    from vgamepad.win.virtual_gamepad import VX360Gamepad, VDS4Gamepad
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "vgamepad\win\virtual_gamepad.py", line 49, in <module>
    VBUS = VBus()
  File "vgamepad\win\virtual_gamepad.py", line 38, in __init__
    check_err(vcli.vigem_connect(self._busp))
  File "vgamepad\win\virtual_gamepad.py", line 15, in check_err
    raise Exception(vcom.VIGEM_ERRORS(err).name)
Exception: VIGEM_ERROR_BUS_NOT_FOUND

1. Run server.exe
2. see error

**Screenshots**
![image](https://user-images.githubusercontent.com/46428822/193127053-666245a3-10e6-459e-913d-f3702ccb0f6e.png)

**Comment by helloparthshah** [comment]
Could you try installing `vgamepad` by doing `pip install vgamepad`

If that still doesn't work then could you try installing https://vigem.org/Downloads/

**Comment by XanderL99** [comment]
That fixed it, thanks!
